[connections.snowflake]
account = "ECBOKFE-MTB60834"
user = "kanjih"
password = "oooooooo"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
